name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_VERCEL_ENV: production
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd freobus-deploy
          npm install
          cd ../freobus-extension
          npm install

      - name: Run Tests
        run: |
          cd freobus-deploy
          npm test

      - name: Build
        run: |
          cd freobus-deploy
          npm run build
        env:
          NEXT_PUBLIC_VERCEL_ENV: production
          NODE_ENV: production

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          cd freobus-deploy
          npm install --global vercel
          vercel deploy --prod --token=$VERCEL_TOKEN 